/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Miguel Ángel
 */
public class Piloto extends javax.swing.JFrame {

    /**
     * Creates new form Piloto
     */
    
    private ControladorPiloto controlador;
    
    
    public Piloto() {
        initComponents();
        
        controlador = new ControladorPiloto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltitud = new javax.swing.JLabel();
        jLabelRumbo = new javax.swing.JLabel();
        jButtonSumarAltitud = new javax.swing.JButton();
        jButtonRestarAltitud = new javax.swing.JButton();
        jButtonSumarRumbo = new javax.swing.JButton();
        jButtonRestarRumbo = new javax.swing.JButton();
        jTextFieldAltitud = new javax.swing.JTextField();
        jTextFieldRumbo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAltitud.setText("Altitud");

        jLabelRumbo.setText("Rumbo");

        jButtonSumarAltitud.setText("+");
        jButtonSumarAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarAltitudActionPerformed(evt);
            }
        });

        jButtonRestarAltitud.setText("-");
        jButtonRestarAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarAltitudActionPerformed(evt);
            }
        });

        jButtonSumarRumbo.setText("+");

        jButtonRestarRumbo.setText("-");

        jTextFieldAltitud.setText("0");
        jTextFieldAltitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAltitudActionPerformed(evt);
            }
        });

        jTextFieldRumbo.setText("0");
        jTextFieldRumbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRumboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAltitud)
                    .addComponent(jLabelRumbo))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSumarRumbo)
                        .addGap(56, 56, 56)
                        .addComponent(jTextFieldRumbo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSumarAltitud)
                        .addGap(56, 56, 56)
                        .addComponent(jTextFieldAltitud, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRestarAltitud, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRestarRumbo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAltitud)
                    .addComponent(jButtonSumarAltitud)
                    .addComponent(jButtonRestarAltitud)
                    .addComponent(jTextFieldAltitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRumbo)
                    .addComponent(jButtonSumarRumbo)
                    .addComponent(jButtonRestarRumbo)
                    .addComponent(jTextFieldRumbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRumboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRumboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRumboActionPerformed

    private void jButtonSumarAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarAltitudActionPerformed
        int nuevaAltitud;
        nuevaAltitud = Integer.parseInt(jTextFieldAltitud.getText());
        nuevaAltitud++;
        if(nuevaAltitud<=40000) jTextFieldAltitud.setText(""+nuevaAltitud);

        try {
            controlador.modificarAltitud();
        } catch (IOException ex) {
            Logger.getLogger(Piloto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSumarAltitudActionPerformed

    private void jTextFieldAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAltitudActionPerformed
               int valor = Integer.parseInt(jTextFieldAltitud.getText());
       
       if(valor<0 || valor>40000) JOptionPane.showMessageDialog(this, "La altitud ha de estar entre 0 y 40000", "Error", JOptionPane.ERROR_MESSAGE);
        
        // Tenemos que llamar al controlador 
       else    try {
           controlador.modificarAltitud();
               } catch (IOException ex) {
                   Logger.getLogger(Piloto.class.getName()).log(Level.SEVERE, null, ex);
               } 
    }//GEN-LAST:event_jTextFieldAltitudActionPerformed

    private void jButtonRestarAltitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarAltitudActionPerformed
        int nuevaAltitud;
        nuevaAltitud = Integer.parseInt(jTextFieldAltitud.getText());
        nuevaAltitud--;
        if(nuevaAltitud>=0) jTextFieldAltitud.setText(""+nuevaAltitud);

        try {
            controlador.modificarAltitud();
        } catch (IOException ex) {
            Logger.getLogger(Piloto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRestarAltitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRestarAltitud;
    private javax.swing.JButton jButtonRestarRumbo;
    private javax.swing.JButton jButtonSumarAltitud;
    private javax.swing.JButton jButtonSumarRumbo;
    private javax.swing.JLabel jLabelAltitud;
    private javax.swing.JLabel jLabelRumbo;
    private javax.swing.JTextField jTextFieldAltitud;
    private javax.swing.JTextField jTextFieldRumbo;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextFieldAltitud() {
        return jTextFieldAltitud;
    }

    public JTextField getjTextFieldRumbo() {
        return jTextFieldRumbo;
    }


}

